<center><h1>Introduction to Python</h1></center>

<strong>
    TF: Maurice Wilson<br>
    Astron 100 Section<br>
    Spring 2021
</strong>


<p>In your remote Linux computer, let's fire up Python.
    <br>Type <em>python3</em> in your terminal.
</p>

In Python, we can check if you have the latest version of Python.  Run the following code, one line at a time.  Hit the <strong>Enter</strong> key to run each line of code. 

In [146]:
import sys
sys.version

'3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]'


<p>This outputs text that should say <strong>'3.8.5 (default, Dec 15 2020, 22:00:44) \n[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]'</strong> on your remote Linux computer.</p>

With the same version of Python, we should all be capable of running the same commands as well as installing and importing the same Python packages.

<br>
Let's work with numbers and simple math operations.

In [147]:
900

900

In [148]:
9+9

18

In [149]:
10/2 # this is division

5.0

In [150]:
10*2 # this is multiplication

20

In [151]:
10*2-3

17

In [152]:
10*(2-3) # Python (like any calculator) understands the proper order of operations: Please Excuse My Dear Aunt Sally (PEMDAS)

-10

In [153]:
10**2 # can you figure out what this is doing?

100

In [154]:
10%2 # can you figure out what this is doing?

0

In [155]:
10//2 # can you figure out what this is doing?

5

In [156]:
10 > 2 # can you figure out what this is doing?

True

In [157]:
10 == 2 # can you figure out what this is doing?

False

In [158]:
False == (10 == 2) # can you figure out what this is doing?  hint: order of operations helps here

True

<br>
Instead of numbers, let's output some text.

In [159]:
print("Hello World!")

Hello World!


That was only one string of text.  Let's print out two strings of text and combine them.

In [160]:
print( "hello" + " darkness, my old friend" )

hello darkness, my old friend


In [161]:
print("7+7")

7+7


When printing text, you cannot perform math operations unless you <em>format</em> your text in a way that tells Python to prepare for non-text based operations.  To do this, use an <strong><em>f</em></strong> immediately before the quotations.  Then, to temporarily exit the text mode, use curly braces: <strong><em>{ }</em></strong>.

In [162]:
print(f"7+7  = { 7+7 }")

7+7  = 14


In [163]:
print( "7+7  = { 7+7 }")  # this is what happens when you forget to use the "f"

7+7  = { 7+7 }


<br>
<h3 style="text-decoration: underline;">Variables</h3>

You can save your output into variables.  That output becomes the value that your variable represents.  Variables can be given any name.  A variable with a single name can have its value vary at any time.  

Execute the 3 following lines of code in your Python command line, one line at a time.

In [164]:
x = 15 #  15 is the value that the 'x' variable represents
y = 3
z = x/y

In [165]:
x

15

In [166]:
y

3

In [167]:
z

5.0

In [168]:
y = 7.5

In [169]:
z  # the 'z' variable still has its original value stored 

5.0

In [170]:
z = x/y  # since 'y' has changed, we need to re-run this line of code in order to store a new value into the 'z' variable

In [171]:
z

2.0

In [172]:
print( z )  # you can 'print' the output of anything: numbers, text, variables, etc.
print( x/y )

2.0
2.0


<br>
Instead of numbers, let's store text into our variables.

In [173]:
car = 'Maserati'
pets = 'cats and dogs'

In [174]:
print(car)
print(pets)

Maserati
cats and dogs


We have variables that store numbers and variables that store text.  Let's print some text that uses both kinds of variables. 

In [175]:
print(f"I have {pets}.")  # the curly braces have you temporarily exit the text mode and places you back into the original Python environment.
print(f"My {x} {pets} drove the {car}!")

I have cats and dogs.
My 15 cats and dogs drove the Maserati!


In [176]:
print(f'My {pets} say "me-ow" or "ruff" when hungry.')  # Using single quotation marks on the outside, you can get double quotation marks on the inside.

My cats and dogs say "me-ow" or "ruff" when hungry.


<br>
<h3 style="text-decoration: underline;">Data Types</h3>

In Python, everything you use (e.g., numbers, text, variables, etc.) is a type of data that Python reads, saves into storage, and uses to perform your commands and calculations.  We can use the <strong><em>type</em></strong> command to understand what type of Python data we are using. 

In [177]:
type(42) # this number is an integer

int

In [178]:
type(42.0) # numbers with decimals are floats.  Now Python knows to be very precise when performing calculations with this number

float

In [179]:
type('42.0') # the data type of text is called a string.

str

In [180]:
print(y)
type(y)

7.5


float

We can change the data type of any value.

In [181]:
int( 42.0 )

42

In [182]:
int( y )  # converting a float into an integer reduces Python's precision. Be careful when changing a value's data type!

7

In [183]:
print( y + y)
print( int(y) + int(y) )

15.0
14


Try these lines of the code in the command line (one line at a time, as usual)

In [184]:
print(       '42.0'   )
print( float('42.0')  )
print(   int('42  ')  )
print(   int('42.0')  ) # this line should give you an error message.

42.0
42.0
42


ValueError: invalid literal for int() with base 10: '42.0'

In [207]:
print(   42.0  + 2  )  # add a float with an integer, and you get a float

print( str(42.0) +  str(2)  ) # convert both numbers to strings and add them together
print( "42.0" +  "2"  )  # same output

print( str(42.0) +  2 ) # this should give you an error message. you cannot add a string with a number (of any type: float or integer)   

44.0
42.02
42.02


TypeError: can only concatenate str (not "int") to str

In [228]:
print( str(42.0) *  2 )  # you can, however, multiply strings
print( str(42.0) *  3 )

42.042.0
42.042.042.0


<br>
Let's practice using the <strong style="text-decoration: underline;">boolean</strong> data type.

In [229]:
verdict_T = True
verdict_F = False

type(verdict_T) 

bool

In [230]:
print(  type(verdict_T)  ) # print the output of the 'type' command

<class 'bool'>


In [231]:
T_or_F =  (5 > 3)  

print(T_or_F)  # is 5 greater than 3?

True


In [232]:
T_or_F =  (5 >= 3)  

print(T_or_F)  # is 5 greater or equal to than 3?

True


In [233]:
T_or_F =  5 > 300  

print(T_or_F)  # is 5 greater than 300?

False


In [234]:
T_or_F =  (5 == 3)  

print(T_or_F)  # is 5 equal to 3?

False


In [235]:
T_or_F =  True == True  

print(T_or_F)  # is True equal to True?

True


<br>
Let's practice using the <strong style="text-decoration: underline;">tuple</strong> data type.

In [236]:
numberset = (5, 20, -3.7)

print(numberset)
print( type(numberset) )

(5, 20, -3.7)
<class 'tuple'>


In [237]:
numberset *2   # similar to strings, a tuple being multiplied does not actually perform mathematical operation

(5, 20, -3.7, 5, 20, -3.7)

In [238]:
len(numberset)  # the 'len' command tells you the length of this set of numbers

3

In [239]:
alpha_omega = ('first', 'last')  
alpha, omega = alpha_omega  # we can assign two values (from the 'alpha_omega' tuple) onto two variables called 'alpha' and 'omega'

print(alpha_omega)
print(alpha)

('first', 'last')
first


<br>
Let's practice using the <strong style="text-decoration: underline;">list</strong> data type. 

In [240]:
mylist = ['fair', alpha, -9.1, False]

print( mylist )
print( type(mylist) )

['fair', 'first', -9.1, False]
<class 'list'>


In [241]:
mylist.append( 'new' )  # we can append more elements to this list

print( mylist )

['fair', 'first', -9.1, False, 'new']


In [242]:
mylist.append( alpha_omega )  # we can append almost anything to a list, including a tuple

print(mylist)

['fair', 'first', -9.1, False, 'new', ('first', 'last')]


<br>
Let's practice using the <strong style="text-decoration: underline;">numpy array</strong> data type. 
<br>
First, we need to import the numpy package.

In [243]:
import numpy as np  # import the package and then give it a nickname.  "np" is the typical nickname given to the numpy package.

In [244]:
arr = np.array([ 36, -5*2 ]) # the package is being called through 'np.' and then 'array' is the command being called

print(arr)
print( type(arr) )
print( len(arr)  )

[ 36 -10]
<class 'numpy.ndarray'>
2


<br>
<h3 style="text-decoration: underline;">Indexing</h3>
<br>
Python starts everything with the number 0.  Not 1.  

In [245]:
mylist[0]  # the first element of this list is called by using 0 as an index

'fair'

In [246]:
mylist[-1] # the last element is called when -1 is the index

('first', 'last')

In [247]:
p = np.arange(10)  # let's automatically generate an array with the 'np.arange'  
print( p )

[0 1 2 3 4 5 6 7 8 9]


In [248]:
p[:] # all elements in this array  

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [249]:
p[1:]  # all elements from beginning to end, starting from the 2nd element 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [250]:
p[1:-2] # include the 2nd element, exclude the last 2 elements, and include everything in between

array([1, 2, 3, 4, 5, 6, 7])

In [251]:
p[ 1:-2: 2] # same as before, except step along the array in increments of 2 elements

array([1, 3, 5, 7])

You can extract different elements and slices of a list, tuple, or array by considering the following indexing methodology:
<br>
<code>list[initial value:final value:step size]</code>
<br>
<br>

In [252]:
np.sum( p )  # take the sum of all numbers in the array

45

In [253]:
np.sum( p[-2:] )  # take the sum of only the last 2 numbers in the array

17

In [254]:
print(f"The last element = { p[-1] }")

The last element = 9


<br>
<h3 style="text-decoration: underline;">Functions</h3>
<br>
If you need multiple lines of code to be ran at once or you need the same series of calculations to repeatedly be ran, then functions can help. 

In your terminal, use a text editor (like nano or vim) to open a file.  You can call the file "section1.py"  Place the following block of code within it.

In [255]:
def myfunct():
    print('I ran it')
    
    fun = 10
    bun = 3
    
    return fun*bun

print( myfunct()  )  # call the function by using parenthesis '()'

I ran it
30


In [256]:
print(fun*bun) # doesn't work outside of function

NameError: name 'fun' is not defined

In [257]:
def simple(mu,gamma):
    
    print(mu + gamma)
    print(mu * gamma)
    print(mu **gamma)
    
    sub = mu - gamma
    
    return sub

print('Go')
result = simple( 3, 4)

print('print result')
print(result)

print('Go again')
result = simple( 10, 2)

print('print result again')
print(result)

Go
7
12
81
print result
-1
Go again
12
20
100
print result again
8


In [ ]:
exec( open('section1.py').read()  )